<div class="backup-page" @if($activity->whereIn('status', ['queued', 'running'])->isNotEmpty()) wire:poll.1500ms @endif>
    <div class="section-title"><div><p class="eyebrow">RESPALDOS</p><h1>{{ $site->domain }}</h1><p class="muted">Cada respaldo conserva archivos del dominio y, cuando aplica, el dump MariaDB del proyecto Laravel.</p></div><a class="secondary" href="{{ route('sites.show', $site) }}">← Sitio</a></div>
    @if(session('notice'))<p class="notice" role="status">{{ session('notice') }}</p>@endif
    <section class="panel"><div class="section-title"><div><h2>Copias disponibles</h2><p>Se conservan en el VPS. Restaurar reemplaza archivos y puede importar la base incluida.</p></div><button class="primary" wire:click="createBackup" wire:loading.attr="disabled">Crear respaldo</button></div>
        @if($backups->isEmpty())<p class="muted">No hay respaldos terminados todavía.</p>@else<div class="database-table-scroll"><table><thead><tr><th>Fecha</th><th>Archivo</th><th>Acción</th></tr></thead><tbody>@foreach($backups as $backup)<tr wire:key="backup-{{ $backup->id }}"><td>{{ $backup->finished_at?->format('d/m/Y H:i') }}</td><td><code>{{ basename(trim($backup->output)) }}</code></td><td><button class="ghost" wire:click="selectBackupForRestore({{ $backup->id }})">Restaurar</button></td></tr>@endforeach</tbody></table></div>@endif
        @if($restoreBackupDeploymentId)<form wire:submit="restoreBackup" class="stack backup-restore-form"><label>Para restaurar esta copia escribe <code>RESTAURAR {{ $site->domain }}</code><input wire:model="restoreConfirmation" autocomplete="off"></label><div class="button-row"><button class="danger-button" wire:loading.attr="disabled">Restaurar respaldo</button><button type="button" class="secondary" wire:click="$set('restoreBackupDeploymentId', null)">Cancelar</button></div></form>@endif
    </section>
    <section class="panel"><h2>Actividad reciente</h2>@forelse($activity as $operation)<div class="activity-row" wire:key="backup-activity-{{ $operation->id }}"><span class="dot {{ $operation->status }}"></span><div><strong>{{ $operation->action === 'backup' ? 'Respaldo' : 'Restauración' }}</strong><p>{{ $operation->output }}</p></div><time>{{ $operation->created_at->diffForHumans() }}</time></div>@empty<p class="muted">Sin operaciones todavía.</p>@endforelse</section>
</div>
