<div x-data="{ tab: 'overview' }">
    <header class="topbar"><a class="brand" href="/"><span class="mark">MP</span> MiniPanel</a><div class="server">{{ $site->domain }} · {{ strtoupper($site->runtime) }}</div><a class="ghost" href="{{ route('sites.files', $site) }}">Archivos</a><a class="ghost" href="/">← Sitios</a></header>
    <section class="hero"><div><p class="eyebrow">OPERACIONES DEL PROYECTO</p><h1>{{ $site->name }}</h1><p class="muted">{{ $site->path }} · última inspección: {{ $site->last_inspected_at?->diffForHumans() ?? 'pendiente' }}</p></div><button wire:click="inspect" class="primary">Inspeccionar proyecto</button></section>
    @if(session('notice'))<div class="notice">{{ session('notice') }}</div>@endif
    <nav class="project-tabs" aria-label="Secciones del proyecto"><button @click="tab = 'overview'" :class="{ 'active': tab === 'overview' }">Resumen</button><button @click="tab = 'operate'" :class="{ 'active': tab === 'operate' }">Operar</button><button @click="tab = 'configure'" :class="{ 'active': tab === 'configure' }">Configurar</button><button @click="tab = 'activity'" :class="{ 'active': tab === 'activity' }">Actividad</button></nav>
    <section class="ops-grid" x-show="tab === 'operate'" x-transition>
        <article class="panel"><h2>Laravel / Artisan</h2><p class="muted">Comandos detectados del proyecto. Cada argumento va en una línea y se audita.</p>
            @if($site->artisan_commands)<form wire:submit="runArtisan" class="stack"><select wire:model="artisanCommand"><option value="">Selecciona un comando</option>@foreach($site->artisan_commands as $command)<option value="{{ $command['name'] }}">{{ $command['name'] }} — {{ $command['description'] }}</option>@endforeach</select><textarea wire:model="artisanArguments" rows="3" placeholder="Argumentos opcionales, uno por línea"></textarea><button class="secondary">Ejecutar Artisan</button></form>@else <p class="muted">Inspecciona el proyecto para descubrir comandos.</p>@endif
        </article>
        <article class="panel"><h2>Llave de despliegue SSH</h2><p class="muted">La llave privada se conserva sólo en el VPS. Copia esta llave pública como Deploy Key en tu proveedor Git.</p>@if($site->deploy_key_public)<textarea class="env-editor" rows="3" readonly>{{ $site->deploy_key_public }}</textarea><div class="button-row"><button wire:click="createDeployKey(true)" class="secondary">Rotar llave</button><button wire:click="removeDeployKey" class="ghost">Revocar del VPS</button></div>@else<button wire:click="createDeployKey" class="secondary">Generar llave SSH</button>@endif</article>
        <article class="panel" x-data="{ visible: false }"><h2>Webhook de deploy</h2><p class="muted">GitHub y GitLab encolan un deploy cuando haces push a <code>{{ $site->branch }}</code>.</p>@if($site->webhook_token)<label>URL<input readonly value="{{ route('webhooks.deploy', $site) }}"></label>@if($newWebhookSecret)<label>Secret — cópialo ahora<input readonly value="{{ $newWebhookSecret }}"></label>@else<p class="muted">El secret sólo se muestra al crear o rotar el webhook.</p>@endif<div class="button-row"><button wire:click="createWebhook" class="secondary">Rotar webhook</button><button wire:click="disableWebhook" class="ghost">Desactivar</button></div>@else<button wire:click="createWebhook" class="secondary">Crear webhook</button>@endif</article>
        <article class="panel" x-data="{ open: true }"><div class="section-title"><div><h2>Composer y NPM</h2><p class="muted">Se ejecutan como el usuario del sitio, sin shell root.</p></div><button type="button" class="ghost" @click="open = !open" x-text="open ? 'Ocultar' : 'Mostrar'"></button></div><div x-show="open" x-transition>
            <form wire:submit="runComposerCommand" class="stack"><label>composer <input wire:model="composerCommand" placeholder="require spatie/laravel-permission"></label><button class="secondary" wire:loading.attr="disabled">Ejecutar Composer</button></form>
            <form wire:submit="runNpmCommand" class="stack"><label>npm <input wire:model="npmCommand" placeholder="run build"></label><button class="secondary" wire:loading.attr="disabled">Ejecutar NPM</button></form>
            <div class="button-row">@foreach($site->npm_scripts ?? [] as $name => $script)<button wire:click="npm('run', @js($name))" class="tiny">npm run {{ $name }}</button> @endforeach</div>
        </div></article>
    </section>
    <section class="panel" x-show="tab === 'configure'" x-transition><div class="section-title"><div><h2>Archivo .env</h2><p>Se guarda cifrado en la base del panel y se aplica por el agente con permisos 0640.</p></div><button wire:click="saveEnvironment" class="primary">Guardar .env</button></div><textarea wire:model="environment" class="env-editor" rows="18" spellcheck="false" placeholder="APP_NAME=...&#10;APP_ENV=production"></textarea></section>
    <section class="panel" x-show="tab === 'configure'" x-transition><div class="section-title"><div><h2>Script de deploy</h2><p>Un comando por línea. Si lo configuras, sustituye la secuencia Laravel predeterminada y corre antes de levantar el sitio. Acepta <code>php artisan</code>, <code>composer</code> y <code>npm</code>; no ejecuta shell.</p></div><button wire:click="saveDeployCommands" class="primary">Guardar script</button></div><textarea wire:model="deployCommands" class="env-editor" rows="9" spellcheck="false" placeholder="composer install --no-dev --dump-autoload&#10;php artisan migrate --force&#10;npm ci&#10;npm run build&#10;php artisan optimize:clear&#10;php artisan optimize"></textarea>@error('deployCommands')<p class="error">{{ $message }}</p>@enderror</section>
    <section class="panel" x-show="tab === 'configure'" x-transition><div class="section-title"><div><h2>Configuración Nginx</h2><p>Directivas dentro del bloque <code>server</code>. Se prueba y revierte automáticamente si Nginx no acepta la configuración.</p></div><button wire:click="saveNginxConfig" class="primary">Aplicar Nginx</button></div><textarea wire:model="nginxConfig" class="env-editor" rows="12" spellcheck="false" placeholder="client_max_body_size 64m;&#10;location /health { return 200; }"></textarea></section>
    <section class="ops-grid" x-show="tab === 'overview'" x-transition>
        <article class="panel" @if($dnsRun && in_array($dnsRun->status, ['queued', 'running'])) wire:poll.1500ms @endif><h2>Salud, DNS y respaldos</h2><div class="stack"><input wire:model="healthUrl" placeholder="https://{{ $site->domain }}"><button wire:click="checkHealth" class="secondary">Verificar salud</button><button wire:click="checkDns" class="secondary">Comprobar propagación DNS</button><button wire:click="backup" class="secondary">Crear backup de archivos</button></div><p class="muted">HTTP: {{ $site->health_status ?? 'sin revisar' }} · Backup: {{ $site->last_backup_at?->diffForHumans() ?? 'nunca' }}</p>@if($site->last_backup_path)<form wire:submit="restoreBackup" class="stack"><label>Para restaurar el último backup escribe <code>RESTAURAR {{ $site->domain }}</code><input wire:model="restoreConfirmation" autocomplete="off"></label><button class="ghost">Restaurar último backup</button></form>@endif @if($dnsRun)<p class="muted">DNS: {{ $dnsRun->status }} @if(in_array($dnsRun->status, ['queued','running']))<button wire:click="cancelDns({{ $dnsRun->id }})" class="ghost">Cancelar</button>@endif</p><div class="dns-results">@foreach($dnsRun->results['checks'] ?? [] as $check)<p><code>{{ $check['resolver'] }}</code> · A: {{ $check['a'] ?: '—' }} · AAAA: {{ $check['aaaa'] ?: '—' }}</p>@endforeach</div>@elseif($site->dns_results)<div class="dns-results">@foreach($site->dns_results['checks'] ?? [] as $check)<p><code>{{ $check['resolver'] }}</code> · A: {{ $check['a'] ?: '—' }} · AAAA: {{ $check['aaaa'] ?: '—' }}</p>@endforeach</div>@endif</article>
        <article class="panel"><h2>Colas y workers</h2><p class="muted">Crea un servicio systemd por worker y cola.</p><form wire:submit="createQueue" class="form-grid"><label>Queue<input wire:model="queueName" placeholder="emails"></label><label>Workers<input wire:model="queueWorkers" type="number" min="1" max="12"></label><label>Tries<input wire:model="queueTries" type="number" min="1" max="20"></label><label>Timeout<input wire:model="queueTimeout" type="number" min="10" max="3600"></label><div class="form-actions"><button class="secondary">Guardar cola</button></div></form>@foreach($queues as $queue)<p><code>{{ $queue->name }}</code> · {{ $queue->workers }} worker(s) · {{ $queue->tries }} tries · {{ $queue->timeout }}s · <span class="ok">{{ $queue->status }}</span> <button wire:click="removeQueue({{ $queue->id }})" class="ghost">Eliminar</button></p>@endforeach</article>
        <article class="panel"><h2>Logs</h2><div class="button-row"><button wire:click="logs('laravel')" class="tiny">Laravel</button><button wire:click="logs('nginx-access')" class="tiny">Nginx access</button><button wire:click="logs('nginx-error')" class="tiny">Nginx error</button><button wire:click="logs('queue')" class="tiny">Queue</button></div></article>
        <article class="panel"><h2>Dominios y rollback</h2><div class="stack"><input wire:model="alias" placeholder="www.{{ $site->domain }}"><button wire:click="addAlias" class="secondary">Añadir alias</button></div>@foreach($site->aliases ?? [] as $alias)<p><code>{{ $alias }}</code> <button wire:click="removeAlias('{{ $alias }}')" class="ghost">Quitar</button></p>@endforeach<div class="stack"><input wire:model="rollbackCommit" placeholder="SHA del commit"><button wire:click="rollback" class="ghost">Rollback al commit</button></div></article>
    </section>
    <section class="panel activity" x-show="tab === 'activity'" x-transition><h2>Actividad</h2>@forelse($activity as $item)<div class="activity-row"><span class="dot {{ $item->status }}"></span><div><strong>{{ $item->action }}</strong><p>{{ $item->output }}</p></div><time>{{ $item->created_at->diffForHumans() }}</time></div>@empty <p class="muted">Sin operaciones todavía.</p>@endforelse</section>
    <section class="panel danger-zone" x-show="tab === 'configure'" x-transition><h2>Zona de peligro</h2><p class="muted">Suspender deshabilita Nginx. Eliminar destruye sitio, vhost, servicios, llaves, backups y la base/usuario MariaDB detectados en su <code>.env</code>. Úsalo sólo si esa base no se comparte.</p>@if($site->status === 'suspended')<button wire:click="resumeSite" class="secondary">Reactivar sitio</button>@else<button wire:click="suspendSite" class="ghost">Suspender sitio</button>@endif<form wire:submit="deleteSite" class="stack"><label>Escribe <code>ELIMINAR {{ $site->domain }}</code><input wire:model="dangerConfirmation" autocomplete="off"></label><button class="danger-button">Eliminar sitio definitivamente</button></form></section>
</div>
